type: Small multiples

datasource:
    en: http://data.euro.who.int/hfadb/
    ru: http://data.euro.who.int/hfadb/

start: 1980
end: 2012

ymin: 0
ymax:
xmin:
xmax:
dpi: 96
width: 960
height: 617
color: red

countries:
- CIS
- CARK
- Eur-A
- Eur-B+C

comparators:
- European Region