type: Small multiples

datasource:
    en: http://data.euro.who.int/hfadb/
    ru: http://data.euro.who.int/hfadb/

start: 1980
end: 2012

ymin: 0
ymax:
xmin:
xmax:
dpi: 75
width: 960
height: 617
color: steelblue

countries:
- Albania
- Bosnia and Herzegovina
- Bulgaria
- Croatia
- Montenegro
- Republic of Moldova
- Romania
- Serbia
- TFYR Macedonia
- Israel
- Slovenia

comparators:
- Eur-A
- Eur-B+C